# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 01:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MADcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique_for_month=True)),
            ],
        ),
        migrations.CreateModel(
            name='MADconApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_restrictions', models.CharField(blank=True, max_length=256)),
                ('first_time', models.BooleanField()),
                ('status', models.CharField(
                    choices=[('P', 'Pending'), ('A', 'Accepetd'), ('W', 'Waitlisted'), ('R', 'Rejected'),
                             ('C', 'Confirmed')], max_length=1)),
                ('madcon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madcon.MADcon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
