# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 00:08
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('madcon', '0002_auto_20170115_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='madconapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
