# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('madcon', '0004_madconapplication_t_shirt_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MADconApplication',
            new_name='Registration',
        ),
    ]
