# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('madcon', '0005_auto_20170115_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madcon',
            name='date',
            field=models.DateField(unique_for_month='date'),
        ),
    ]
