# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 15:55
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('madcon', '0006_auto_20170117_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='t_shirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')],
                                   default='XS', max_length=3),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
