# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-05 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madcon', '0007_auto_20170118_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='madcon',
            options={'verbose_name': 'MADcon', 'verbose_name_plural': 'MADcons'},
        ),
    ]
