# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-16 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madcon', '0008_auto_20170205_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='madcon',
            name='registration_open',
            field=models.BooleanField(default=False),
        ),
    ]
